export  'package:flutter/material.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:islam_made_easy/generated/l10n.dart';
export 'package:islam_made_easy/layout/adaptive.dart';
export 'package:islam_made_easy/widgets/appBar.dart';
export 'package:islam_made_easy/widgets/chipWidget.dart';
export 'package:islam_made_easy/widgets/infoCard.dart';
export 'package:islam_made_easy/widgets/buttons/tileButton.dart';
export 'package:islam_made_easy/widgets/viewText.dart';