name: islam-made-easy
version: 0.1.0
summary: Islamic Quiz app to understand your religion easier.
description:  Islamic Quiz application that let you understand your religion easier.

confinement: classic
base: core18
grade: stable

slots:
  dbus-islam-made-easy:
    interface: dbus
    bus: session
    name: com.ime.islam_made_easy

apps:
  islam-made-easy:
    command: islam-made-easy
    extensions: [ flutter-master ] # Where "master" defines which Flutter channel to use for the build
    slots:
      - dbus-islam-made-easy
    plugs:
      - network

parts:
  islam-made-easy:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
