name: islam-made-easy
version: 1.0.0
summary: Unveiling the Beauty of Islam, Effortlessly.
description: Islam Made Easy  is a comprehensive Linux application designed to
            facilitate easy and interactive learning about Islam. This app serves as a
            valuable resource for individuals seeking to enhance their knowledge and
            understanding of religion through quizzes and informative content. With its
            user-friendly interface and comprehensive features, IME is your
            ultimate companion to navigate the teachings and principles of Islam effortlessly.

confinement: strict
base: core18
grade: stable

slots:
  dbus-islam-made-easy:
    interface: dbus
    bus: session
    name: com.ime.islam_made_easy

apps:
  islam-made-easy:
    command: islam_made_easy
    extensions: [ flutter-stable ] # Where "stable" defines which Flutter channel to use for the build
    slots:
      - dbus-islam-made-easy
    plugs:
      - network

parts:
  islam-made-easy:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
