name: IME Linux Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - run: ./dist/linux_deb.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/linux/x64/release/islam_made_easy"
          token: ${{ secrets.TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
          prerelease: false

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: linux
          path: build/islam_made_easy.deb


