name: IME MacOS Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 'beta'
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos
