name: IME Windows Releases

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - run: flutter config --enable-windows-desktop

      - name: Run tests
        run: flutter test

      - name: Build APP
        run: flutter build windows

#      - name: Build Installer
#        run: |
#          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "windows_inno_setup.iss"
#        shell: cmd
#      - name: Upload Installer
#        uses: actions/upload-artifact@v2
#        with:
#          name: IME setup.exe.zip
#          path: build\islam_made_easy.exe

      - name: Build msix
        run: flutter pub run msix:create

      - name: Upload msix
        uses: actions/upload-artifact@v2
        with:
          name: IME.msix.zip
          path: build\windows\runner\Release\islam_made_easy.msix
